backend:
  name: git-gateway
  branch: main

media_folder: "pdf"
public_folder: "/pdf"

collections:
  - name: "pdfs"
    label: "Katalog PDF"
    files:
      - name: "data"
        label: "Data PDF"
        file: "data/pdfs.json"
        fields:
          - { label: "Terakhir Update", name: "updated_at", widget: "datetime" }
          - label: "Daftar PDF"
            name: "items"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Tanggal", name: "updated_at", widget: "datetime" }
              - { label: "File PDF", name: "url", widget: "file" }
