backend:
  name: git-gateway
  branch: main

# Lokasi file upload (PDF)
media_folder: "pdf"
public_folder: "/pdf"

# Tampilan editor CMS
publish_mode: simple
locale: "id"

collections:
  - name: "katalog"
    label: "Katalog PDF"
    files:
      - name: "data_pdf"
        label: "Data PDF"
        file: "data/pdfs.json"
        format: "json"
        fields:
          - label: "Daftar PDF"
            name: "items"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Judul"
                name: "title"
                widget: "string"

              - label: "File PDF"
                name: "url"
                widget: "file"
