backend:
  name: github
  # GANTI ini: username/nama-repo (contoh: neo/katalog-pdf)
  repo: username/nama-repo
  branch: main

media_folder: "pdf"
public_folder: "/pdf"

collections:
  - name: "pdfs"
    label: "Katalog PDF"
    files:
      - name: "data"
        label: "Data PDF"
        file: "data/pdfs.json"
        fields:
          - { label: "Terakhir Update", name: "updated_at", widget: "datetime" }
          - label: "Daftar PDF"
            name: "items"
            widget: "list"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Deskripsi", name: "desc", widget: "text" }
              - { label: "Kategori", name: "category", widget: "string" }
              - { label: "File PDF", name: "url", widget: "file" }
              - { label: "Tanggal Update", name: "updated_at", widget: "datetime" }
